resources:
  repositories:
    - repository: corechapter4
      type: git
      name: WizPipelines/core-chapter4

trigger:
  branches:
    exclude: [ 'refs/heads/feature/*' ] # nomes de branchs que n達o ir達o rodar o pipeline
  paths:
    exclude: [ 'README.md' ] # caminhos de arquivos que n達o ir達o rodar o pipeline

extends:
  chapter4: main.yml@corechapter4
  parameters:
    technology: 'dotnetcore'
    azResourceName: 'TO DO eg. customer'
    azWebAppNameUAT: 'TO DO eg. api-customer-hml'
    azWebAppNamePRD: 'TO DO eg. api-customer-prd'
    azSubscriptionUAT: 'TO DO'
    azSubscriptionPRD: 'TO DO'
    dotnetcoreDotNetVersion: '3.x'
    dotnetcoreBuildProject: '**/*[API].csproj'
    dotnetcoreBuildConfiguration: Release
    dotnetcoreTestProject: '**/*[Tt]ests/*.csproj'
    dotnetcoreNugetFeed: 00000000-0000-0000-0000-000000000000
    instrumentationKey: "00000000-0000-0000-0000-000000000000"
